version: "3.8"
services:
  mssql-db:
    container_name: mssql-db
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Everyhappy2
    networks:
      bridge-001:
    volumes:
      - C:\DockerDb:/var/opt/mssql/data
  charlotte-backend:
    container_name: charlotte-backend
    image: pzps94038/charlotte-backend
    ports:
      - "8080:80"
    networks:
      bridge-001:
    volumes:
      - C:\Charlotte-backend/Logs:/var/Charlotte-backend/Logs
      - C:\Charlotte-backend/FileUpload:/app/FileUpload
  charlotte-frontend:
    container_name: charlotte-frontend
    image: pzps94038/charlotte-frontend
    ports:
      - "80:80"
    networks:
      bridge-001:
networks:
  bridge-001: