version: "3.8"
services:
  mssql-db:
    container_name: mssql-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Everyhappy2
    networks:
      bridge-001:
    volumes:
      - /home/charlotte/dockerDb:/var/opt/mssql/data
  redis-db:
    restart: always
    container_name: redis-db
    image: redis:latest
    ports:  
      - 6380:6379
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass Everyhappy2
    networks:
      bridge-001:
    volumes:
      - /home/charlotte/redisDb:/data
      - /home/charlotte/redisDb/redis.conf:/usr/local/etc/redis/redis.conf
  charlotte-backend:
    container_name: charlotte-backend
    image: pzps94038/charlotte-backend:latest
    ports:
      - "8080:80"
    networks:
      bridge-001:
    volumes:
      - /home/charlotte/backend/Logs:/var/Charlotte-backend/Logs
      - /home/charlotte/backend/FileUpload:/app/FileUpload
  charlotte-frontend:
    container_name: charlotte-frontend
    image: pzps94038/charlotte-frontend:latest
    ports:
      - "80:80"
    networks:
      bridge-001:
networks:
  bridge-001: